export const restaurantList =
	// 20230226204838
	// https://www.swiggy.com/dapi/restaurants/list/v5?lat=26.4831584&lng=84.43655&page_type=DESKTOP_WEB_LISTING

	{
		statusCode: 0,
		data: {
			cacheExpiryTime: 320,
			pages: 1,
			pageIndex: 0,
			scrubber: 0,
			filters: [
				{
					type: 'FilterWidget',
					title: 'Cuisines',
					key: 'CUISINES',
					configType: 'checkbox',
					visible: 1,
					options: [
						{
							option: 'American',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Arabian',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Beverages',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Biryani',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Chinese',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Desserts',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Fast Food',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Ice Cream',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Indian',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Italian',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Kebabs',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Mughlai',
							selected: 0,
							visible: 1,
						},
						{
							option: 'North Indian',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Pastas',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Pizzas',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Snacks',
							selected: 0,
							visible: 1,
						},
						{
							option: 'South Indian',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Sweets',
							selected: 0,
							visible: 1,
						},
					],
					detail: '',
					heading: 'Cuisines',
					applicable: 1,
					searchable: 1,
				},
				{
					type: 'FilterWidget',
					title: 'Show Restaurants With',
					key: 'SHOW_RESTAURANTS_WITH',
					configType: 'checkbox',
					visible: 1,
					options: [
						{
							option: 'Offers',
							selected: 0,
							visible: 1,
						},
						{
							option: 'Pure Veg',
							selected: 0,
							visible: 1,
						},
					],
					detail: '',
					heading: 'Offers & More',
					applicable: 1,
					searchable: 0,
				},
			],
			sorts: [
				{
					type: 'SortWidget',
					key: 'RELEVANCE',
					title: 'Relevance',
					selected: 1,
					visible: 1,
					defaultSelection: true,
				},
				{
					type: 'SortWidget',
					key: 'DELIVERY_TIME',
					title: 'Delivery Time',
					selected: 0,
					visible: 1,
					defaultSelection: false,
				},
				{
					type: 'SortWidget',
					key: 'RATING',
					title: 'Rating',
					selected: 0,
					visible: 1,
					defaultSelection: false,
				},
				{
					type: 'SortWidget',
					key: 'COST_FOR_TWO',
					title: 'Cost: Low to High',
					selected: 0,
					visible: 1,
					defaultSelection: false,
				},
				{
					type: 'SortWidget',
					key: 'COST_FOR_TWO_H2L',
					title: 'Cost: High to Low',
					selected: 0,
					visible: 1,
					defaultSelection: false,
				},
			],
			configs: {
				ribbons: {
					PREORDER: {
						type: 'PREORDER',
						text: 'Preorder',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#d53d4c',
						bottomBackgroundColor: '#af2330',
						priority: 3,
					},
					EXCLUSIVE: {
						type: 'EXCLUSIVE',
						text: 'Exclusive',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#fa4a5b',
						bottomBackgroundColor: '#d12a3b',
						priority: 2,
					},
					NEW: {
						type: 'NEW',
						text: 'Newly Added',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#d53d4c',
						bottomBackgroundColor: '#af2330',
						priority: 4,
					},
					REPEAT: {
						type: 'REPEAT',
						text: 'Repeat',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#D53D4C',
						bottomBackgroundColor: '#B02331',
						priority: 6,
					},
					CLOUD: {
						type: 'CLOUD',
						text: 'Daily Menus',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#fa4a5b',
						bottomBackgroundColor: '#d12a3b',
						priority: 5,
					},
					PREMIUM: {
						type: 'PREMIUM',
						text: 'Premium',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#8a584b',
						bottomBackgroundColor: '#583229',
						priority: 7,
					},
					PROMOTED: {
						type: 'PROMOTED',
						text: 'Promoted',
						textColor: '#ffffff',
						imageId: 'sfefefefeegeg',
						topBackgroundColor: '#3a3c41',
						bottomBackgroundColor: '#1e2023',
						priority: 1,
					},
				},
			},
			cards: [
				{
					cardType: 'carousel',
					layoutAlignmentType: 'VERTICAL',
					data: {
						type: 'carousel',
						subtype: 'topCarousel',
						data: {
							cards: [
								{
									type: 'carouselElement',
									subtype: 'image',
									data: {
										bannerId: 635529,
										creativeId:
											'rng/md/carousel/production/pneknawbadtvceqzwiep',
										type: 'restaurantCollectionV2',
										link: '49301',
										cityId: 0,
										restaurantUuid: '',
										restaurantParentId: '0',
										thirdPartyVendor: '',
										thirdPartyAddress: false,
									},
								},
								{
									type: 'carouselElement',
									subtype: 'image',
									data: {
										bannerId: 607193,
										creativeId:
											'rng/md/carousel/production/s5ug2key6e2sptaxku5v',
										type: 'restaurantCollectionV2',
										link: '56410',
										cityId: 0,
										restaurantUuid: '',
										restaurantParentId: '0',
										thirdPartyVendor: '',
										thirdPartyAddress: false,
									},
								},
								{
									type: 'carouselElement',
									subtype: 'image',
									data: {
										bannerId: 607188,
										creativeId:
											'rng/md/carousel/production/oxe97jexxbnxqtbhg2zo',
										type: 'restaurantCollectionV2',
										link: '11740',
										cityId: 0,
										restaurantUuid: '',
										restaurantParentId: '0',
										thirdPartyVendor: '',
										thirdPartyAddress: false,
									},
								},
								{
									type: 'carouselElement',
									subtype: 'image',
									data: {
										bannerId: 607195,
										creativeId:
											'rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3',
										type: 'restaurantCollectionV2',
										link: '56421',
										cityId: 0,
										restaurantUuid: '',
										restaurantParentId: '0',
										thirdPartyVendor: '',
										thirdPartyAddress: false,
									},
								},
							],
						},
					},
					parentWidget: false,
				},
				{
					cardType: 'carousel',
					layoutAlignmentType: 'VERTICAL',
					data: {
						type: 'carousel',
						subtype: 'openFilter',
						data: {
							cards: [
								{
									type: 'carouselElement',
									subtype: 'image',
									data: {
										bannerId: 181684,
										creativeId: 'bkhjfipzydkoqncrxpyi',
										type: 'restaurantCollectionV2',
										link: '11718',
										cityId: 0,
										restaurantUuid: '',
										restaurantParentId: '0',
										title: 'Offers Near You',
										subtitle: '0 OPTIONS',
										restaurants: [],
										totalCount: 0,
										dwebOpenFilterTitle: 'Offers Near You',
										dwebOpenFilterBgColor: '#FF0000',
										dwebOpenFilterSelectIcon:
											'eyperwsfhaoa5vktjtu4',
										dwebOpenFilterDeselectIcon:
											'urw8usdf4mk9aywd59gq',
									},
								},
								{
									type: 'carouselElement',
									subtype: 'image',
									data: {
										bannerId: 181680,
										creativeId: 'a3jqjjod5taken7dh1bs',
										type: 'restaurantCollectionV2',
										link: '11721',
										cityId: 0,
										restaurantUuid: '',
										restaurantParentId: '0',
										title: 'Veg Only',
										subtitle: '0 OPTIONS',
										restaurants: [],
										totalCount: 0,
										dwebOpenFilterTitle:
											'Vegetarian Options',
										dwebOpenFilterBgColor: '#FF0000',
										dwebOpenFilterSelectIcon:
											'qtjc8dzfexg72lug37a0',
										dwebOpenFilterDeselectIcon:
											'bm8bziikwyvwqsml1clm',
									},
								},
							],
						},
					},
					parentWidget: false,
				},
				{
					cardType: 'seeAllRestaurants',
					layoutAlignmentType: 'VERTICAL',
					data: {
						type: 'seeAllRestaurants',
						data: {
							title: 'SEE ALL',
							totalOpenRestaurants: 29,
							cards: [
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '543490',
										name: 'Original Al baik, The Taste of saudi  Arabia',
										uuid: '6f0cc324-f0ae-496c-bb78-12471cad3b91',
										city: '10501',
										area: 'Post Office Chowk',
										totalRatingsString: '50+ ratings',
										cloudinaryImageId:
											'ahyrsgnyb0mozeezavyk',
										cuisines: [
											'North Indian',
											'American',
											'Fast Food',
											'Snacks',
										],
										tags: [],
										costForTwo: 25000,
										costForTwoString: '₹250 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.5999999046325684,
										slugs: {
											restaurant:
												'original-al-baik,-the-taste-of-saudi-arabia-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'near post office chowk, beside Baibhav hotel, banjari road, gopalganj 841428',
										locality: 'Gopalganj Town',
										parentId: 326614,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										ribbon: [
											{
												type: 'PROMOTED',
											},
										],
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID:
											'cid=6002941~p=1~eid=00000186-8e4d-f290-3c74-a69900860120',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.5 kms',
										hasSurge: false,
										sla: {
											restaurantId: '543490',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.5999999046325684,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: true,
										avgRating: '3.7',
										totalRatings: 50,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '487885',
										name: 'The Hot Chinese',
										uuid: '45dc3dc4-13e2-4feb-8afb-2499061b54c2',
										city: '10501',
										area: 'Gopalganj Town',
										totalRatingsString: 'Too Few Ratings',
										cloudinaryImageId:
											'eidkfpcynkgcwyyp5dxg',
										cuisines: ['Chinese'],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 23,
										minDeliveryTime: 23,
										maxDeliveryTime: 23,
										slaString: '23 MINS',
										lastMileTravel: 1.899999976158142,
										slugs: {
											restaurant:
												'food-palace-roll-point-the-hot-chinese-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'YADOPUR ROAD W NO 12, NEAR AXICE BANK A, TM OPP SINGH MEDICAL, GOPALGANJ GOPALGAN, Gopalganj, Gopalganj, Gopalganj, Bihar - 841428',
										locality: 'Gopalganj Town',
										parentId: 209663,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '20% off',
											shortDescriptionList: [
												{
													meta: '20% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '20% off up to ₹50 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '20% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '20% off up to ₹50 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: 'Closes soon',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '1.8 kms',
										hasSurge: false,
										sla: {
											restaurantId: '487885',
											deliveryTime: 23,
											minDeliveryTime: 23,
											maxDeliveryTime: 23,
											lastMileTravel: 1.899999976158142,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '--',
										totalRatings: 0,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '203118',
										name: 'Laxmi Hotel & Restaurant',
										uuid: '33785b13-0d61-47db-8a92-32aab5bc21b2',
										city: '10501',
										area: 'Yadopur Road',
										totalRatingsString: '500+ ratings',
										cloudinaryImageId:
											'unlao0c30xndimiquuts',
										cuisines: [
											'North Indian',
											'Italian',
											'Chinese',
										],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 23,
										minDeliveryTime: 23,
										maxDeliveryTime: 23,
										slaString: '23 MINS',
										lastMileTravel: 1.600000023841858,
										slugs: {
											restaurant:
												'laxmi-hotel-restaurant-yadopur-road-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address: 'YADOPUR ROAD, GOPALGANJ',
										locality: 'YADOPUR ROAD',
										parentId: 123944,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: 'FREE DELIVERY',
											shortDescriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
												{
													meta: 'Free Freebie on orders above ₹499',
													discountType: 'Freebie',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
												{
													meta: 'Free Freebie on orders above ₹499',
													discountType: 'Freebie',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '',
											shortDescriptionList: [
												{
													meta: 'Free Delivery',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
												{
													meta: 'Free Freebie on orders above ₹499',
													discountType: 'Freebie',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '1.6 kms',
										hasSurge: false,
										sla: {
											restaurantId: '203118',
											deliveryTime: 23,
											minDeliveryTime: 23,
											maxDeliveryTime: 23,
											lastMileTravel: 1.600000023841858,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '3.7',
										totalRatings: 500,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '203113',
										name: "Today's Pizza",
										uuid: '2079aae0-1965-45a8-834e-6ad5d0850998',
										city: '10501',
										area: 'Town Thana',
										totalRatingsString: '5000+ ratings',
										cloudinaryImageId:
											'ick8actxmkhz9jhdaxip',
										cuisines: [
											'North Indian',
											'Chinese',
											'Italian',
										],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.5999999046325684,
										slugs: {
											restaurant:
												'todays-pizza-yadopur-road-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'MAIN RD, MURLI MARKET, GOPALGANJ',
										locality: 'YADOPUR ROAD',
										parentId: 216958,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '30% off',
											shortDescriptionList: [
												{
													meta: '30% off | Use JUMBO',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '30% off up to ₹150 on orders above ₹400 | Use code JUMBO',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '30% OFF',
											shortDescriptionList: [
												{
													meta: 'Use JUMBO',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '30% off up to ₹150 on orders above ₹400 | Use code JUMBO',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										ribbon: [
											{
												type: 'PROMOTED',
											},
										],
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID:
											'cid=6002638~p=4~eid=00000186-8e4d-f290-3c74-a69a0086043e',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.5 kms',
										hasSurge: false,
										sla: {
											restaurantId: '203113',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.5999999046325684,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: true,
										avgRating: '3.8',
										totalRatings: 5000,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '517907',
										name: 'Food king',
										uuid: '33f05ab3-a7c8-4d29-84e5-29c3e0239eaa',
										city: '10501',
										area: 'Banjari Road',
										totalRatingsString: '20+ ratings',
										cloudinaryImageId:
											'j96lxqkk5lnzozglztvw',
										cuisines: [
											'North Indian',
											'South Indian',
											'Snacks',
											'Fast Food',
											'Pizzas',
										],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 23,
										minDeliveryTime: 23,
										maxDeliveryTime: 23,
										slaString: '23 MINS',
										lastMileTravel: 1.899999976158142,
										slugs: {
											restaurant:
												'food-king-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'Banjari road In front of kotak mahindra bank ?????????????????? ??????????- 841428',
										locality: 'Gopalganj Town',
										parentId: 81526,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '1.8 kms',
										hasSurge: false,
										sla: {
											restaurantId: '517907',
											deliveryTime: 23,
											minDeliveryTime: 23,
											maxDeliveryTime: 23,
											lastMileTravel: 1.899999976158142,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '3.5',
										totalRatings: 20,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '608033',
										name: "Domino's Pizza",
										uuid: '33638d50-b4a2-43a7-8dab-d77157988f2a',
										city: '10501',
										area: 'Gopalganj',
										totalRatingsString: '50+ ratings',
										cloudinaryImageId:
											'xye5lg4snoojnwmjqamk',
										cuisines: [
											'Pizzas',
											'Italian',
											'Pastas',
											'Desserts',
										],
										tags: [],
										costForTwo: 40000,
										costForTwoString: '₹400 FOR TWO',
										deliveryTime: 25,
										minDeliveryTime: 25,
										maxDeliveryTime: 25,
										slaString: '25 MINS',
										lastMileTravel: 0,
										slugs: {
											restaurant:
												'dominos-pizza-gopalganj-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'Ground Floor, Janak Super Market,College Road, Goplaganj,Bihar:841427',
										locality: 'Gopalganj',
										parentId: 2456,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: 'FREE DELIVERY',
											shortDescriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '',
											shortDescriptionList: [
												{
													meta: 'Free Delivery',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										hasSurge: false,
										sla: {
											restaurantId: '608033',
											deliveryTime: 25,
											minDeliveryTime: 25,
											maxDeliveryTime: 25,
											lastMileTravel: 0,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '4.3',
										totalRatings: 50,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '489777',
										name: 'The Biryani Mall',
										uuid: '4cdf95de-d228-452c-9df0-3362fb2d475d',
										city: '10501',
										area: 'Gopalganj Town',
										totalRatingsString: '100+ ratings',
										cloudinaryImageId:
											'azbvczriemzbbjkop39r',
										cuisines: [
											'Biryani',
											'Chinese',
											'North Indian',
											'Mughlai',
										],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 35,
										minDeliveryTime: 35,
										maxDeliveryTime: 35,
										slaString: '35 MINS',
										lastMileTravel: 2.0999999046325684,
										slugs: {
											restaurant:
												'pizza-express-the-biryani-mall-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'SADHU MARKET, YADOPUR ROAD, GOPALGANJ',
										locality: 'Sadhu Market',
										parentId: 205457,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '60% off',
											shortDescriptionList: [
												{
													meta: '60% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '60% off up to ₹120 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '60% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '60% off up to ₹120 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										ribbon: [
											{
												type: 'PROMOTED',
											},
										],
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID:
											'cid=6002932~p=7~eid=00000186-8e4d-f290-3c74-a69b00860753',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2 kms',
										hasSurge: false,
										sla: {
											restaurantId: '489777',
											deliveryTime: 35,
											minDeliveryTime: 35,
											maxDeliveryTime: 35,
											lastMileTravel: 2.0999999046325684,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: true,
										avgRating: '3.7',
										totalRatings: 100,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '433921',
										name: 'Tandoori House',
										uuid: 'd916c7cd-d82a-43b7-8cce-598f4e462f38',
										city: '10501',
										area: 'Gopalganj Town',
										totalRatingsString: 'Too Few Ratings',
										cloudinaryImageId:
											'pe2epdgugt2y8pqfp99n',
										cuisines: ['North Indian'],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.0999999046325684,
										slugs: {
											restaurant:
												'food-point-&-tandoori-house-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'Yadopur road near Cenra bank indian overseas bank compound Gopalaganj, Gopalganj, Gopalganj, Gopalganj, Bihar, 841428',
										locality: 'Gopalganj Town',
										parentId: 15087,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: 'FREE DELIVERY',
											shortDescriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '',
											shortDescriptionList: [
												{
													meta: 'Free Delivery',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: 'FREE DELIVERY',
													discountType:
														'FREE_DELIVERY',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2 kms',
										hasSurge: false,
										sla: {
											restaurantId: '433921',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.0999999046325684,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '--',
										totalRatings: 0,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '682293',
										name: 'Wings N Pizza\t',
										uuid: '3ba01526-8060-4f63-af7c-d3ed485f8d01',
										city: '10501',
										area: 'Gopalganj Town',
										totalRatingsString: 'Too Few Ratings',
										cloudinaryImageId:
											'54e2acd86733cb07f4f1514b5df90aed',
										cuisines: [
											'Beverages',
											'Ice Cream',
											'Desserts',
										],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.9000000953674316,
										slugs: {
											restaurant:
												'wings-n-pizza-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'Janta Cinema Road, Ward No. 17, Aliraja  Petrol Pump ke Samne, Kedar Market,  Gopalganj, Gopalganj, Gopalganj, Bihar -  841428',
										locality: 'Janta Cinema Road',
										parentId: 226112,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '30% off',
											shortDescriptionList: [
												{
													meta: '30% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '30% off up to ₹75 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '30% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '30% off up to ₹75 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.9 kms',
										hasSurge: false,
										sla: {
											restaurantId: '682293',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.9000000953674316,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '--',
										totalRatings: 0,
										new: true,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '377803',
										name: 'FOOD POINT',
										uuid: 'cae3f237-71fb-4f6b-866d-cd80dae40108',
										city: '10501',
										area: 'Near Cenara Bank',
										totalRatingsString: '100+ ratings',
										cloudinaryImageId:
											'xuiprjpc6pr0eghdxccr',
										cuisines: ['Indian'],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 37,
										minDeliveryTime: 37,
										maxDeliveryTime: 37,
										slaString: '37 MINS',
										lastMileTravel: 2.4000000953674316,
										slugs: {
											restaurant:
												'food-point-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'\tYadopur road near Cenra bank indian overseas bank compound Gopalaganj, Gopalganj, Gopalganj, Gopalganj, Bihar, 841428',
										locality: 'Gopalganj Town',
										parentId: 3967,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										ribbon: [
											{
												type: 'PROMOTED',
											},
										],
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID:
											'cid=6002968~p=10~eid=00000186-8e4d-f290-3c74-a69c00860a16',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.4 kms',
										hasSurge: false,
										sla: {
											restaurantId: '377803',
											deliveryTime: 37,
											minDeliveryTime: 37,
											maxDeliveryTime: 37,
											lastMileTravel: 2.4000000953674316,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: true,
										avgRating: '3.6',
										totalRatings: 100,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '608648',
										name: 'Grill Inn',
										uuid: '5f1ffc59-23c7-4051-ab5c-e02e5fd5243d',
										city: '10501',
										area: 'Gopalganj Town',
										totalRatingsString: '20+ ratings',
										cloudinaryImageId:
											'hdtb3ixkahf4tlmhv0zc',
										cuisines: [
											'Pizzas',
											'Snacks',
											'Fast Food',
										],
										tags: [],
										costForTwo: 25000,
										costForTwoString: '₹250 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.700000047683716,
										slugs: {
											restaurant:
												'awesome-foodtech-private-limited-grill-inn-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'OPP RAJEEV REGENCY HOTEL NH 27  SAREYA NEAR BANJARI MORE  GOPALGANJ, Gopalganj, Gopalganj,  Bihar, 841428',
										locality: 'Gopalganj Town',
										parentId: 432,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.7 kms',
										hasSurge: false,
										sla: {
											restaurantId: '608648',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.700000047683716,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '4.2',
										totalRatings: 20,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '218749',
										name: 'Gaurishankar Sudh Misthan Bhandar',
										uuid: 'e5dac5bc-9772-4156-a419-0c017e002956',
										city: '10501',
										area: 'Haziapur',
										totalRatingsString: '100+ ratings',
										cloudinaryImageId:
											'u0pdecwzqb36rdspanjg',
										cuisines: ['Sweets'],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.4000000953674316,
										slugs: {
											restaurant:
												'gaurishankar-sudh-misthan-bhandar-near-canara-bank-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'JADAVPUR ROAD NEAR CANARA BANK GOPALGANJ',
										locality: 'NEAR CANARA BANK',
										parentId: 86658,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: 'Closes soon',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.4 kms',
										hasSurge: false,
										sla: {
											restaurantId: '218749',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.4000000953674316,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '4.3',
										totalRatings: 100,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '203125',
										name: 'Food Plaza',
										uuid: '412dafdd-63b5-492b-831c-486048e4ea8a',
										city: '10501',
										area: 'Police Line',
										totalRatingsString: '1000+ ratings',
										cloudinaryImageId:
											'be2gdbjsqukocqnerepl',
										cuisines: [
											'North Indian',
											'Italian',
											'Chinese',
										],
										tags: [],
										costForTwo: 10000,
										costForTwoString: '₹100 FOR TWO',
										deliveryTime: 32,
										minDeliveryTime: 32,
										maxDeliveryTime: 32,
										slaString: '32 MINS',
										lastMileTravel: 2.0999999046325684,
										slugs: {
											restaurant:
												'food-plaza-yadopur-road-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'SADHU MARKET, YADOPUR ROAD, GOPALGANJ',
										locality: 'YADOPUR ROAD',
										parentId: 3966,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										ribbon: [
											{
												type: 'PROMOTED',
											},
										],
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID:
											'cid=6002918~p=13~eid=00000186-8e4d-f290-3c74-a69d00860d7d',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2 kms',
										hasSurge: false,
										sla: {
											restaurantId: '203125',
											deliveryTime: 32,
											minDeliveryTime: 32,
											maxDeliveryTime: 32,
											lastMileTravel: 2.0999999046325684,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: true,
										avgRating: '3.5',
										totalRatings: 1000,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '321002',
										name: 'PizzaExpress',
										uuid: '0efb2d9b-b63b-43c4-9a95-9a374452ddae',
										city: '10501',
										area: 'Police Line',
										totalRatingsString: '500+ ratings',
										cloudinaryImageId:
											'gwnnl2ktfwxdezvcgdqy',
										cuisines: ['Indian', 'Chinese'],
										tags: [],
										costForTwo: 15000,
										costForTwoString: '₹150 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.0999999046325684,
										slugs: {
											restaurant:
												'sudh-sakahari-gopalganj-town-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'Near Kailash Hotel Yadopur Road  Gopalganj',
										locality: 'Gopalganj Town',
										parentId: 3531,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2 kms',
										hasSurge: false,
										sla: {
											restaurantId: '321002',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.0999999046325684,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '3.3',
										totalRatings: 500,
										new: false,
									},
									subtype: 'basic',
								},
								{
									type: 'restaurant',
									data: {
										type: 'F',
										id: '218763',
										name: 'K Chowdhary Sweet House',
										uuid: '638afce9-7ae6-45a0-a03c-2f782e7e8e9b',
										city: '10501',
										area: 'Banakata',
										totalRatingsString: '100+ ratings',
										cloudinaryImageId:
											'lfvs1nsrqeppfskwwner',
										cuisines: ['Sweets'],
										tags: [],
										costForTwo: 20000,
										costForTwoString: '₹200 FOR TWO',
										deliveryTime: 26,
										minDeliveryTime: 26,
										maxDeliveryTime: 26,
										slaString: '26 MINS',
										lastMileTravel: 2.5,
										slugs: {
											restaurant:
												'k-chowdhary-sweet-house-near-petrol-pump-gopalganj-town',
											city: 'gopalganj',
										},
										cityState: '10501',
										address:
											'K CHOWDHARY SWEET HOUSE, CINEMA ROAD GOPALGANJ',
										locality: 'NEAR PETROL PUMP',
										parentId: 112661,
										unserviceable: false,
										veg: false,
										select: false,
										favorite: false,
										tradeCampaignHeaders: [],
										aggregatedDiscountInfo: {
											header: '50% off',
											shortDescriptionList: [
												{
													meta: '50% off | Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										aggregatedDiscountInfoV2: {
											header: '50% OFF',
											shortDescriptionList: [
												{
													meta: 'Use TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											descriptionList: [
												{
													meta: '50% off up to ₹100 | Use code TRYNEW',
													discountType: 'Percentage',
													operationType: 'RESTAURANT',
												},
											],
											subHeader: '',
											headerType: 0,
											superFreedel: '',
										},
										chain: [],
										feeDetails: {
											fees: [],
											totalFees: 0,
											message: '',
											title: '',
											amount: '',
											icon: '',
										},
										availability: {
											opened: true,
											nextOpenMessage: '',
											nextCloseMessage: '',
										},
										longDistanceEnabled: 0,
										rainMode: 'NONE',
										thirdPartyAddress: false,
										thirdPartyVendor: '',
										adTrackingID: '',
										badges: {
											imageBased: [],
											textBased: [],
											textExtendedBadges: [],
										},
										lastMileTravelString: '2.5 kms',
										hasSurge: false,
										sla: {
											restaurantId: '218763',
											deliveryTime: 26,
											minDeliveryTime: 26,
											maxDeliveryTime: 26,
											lastMileTravel: 2.5,
											lastMileDistance: 0,
											serviceability: 'SERVICEABLE',
											rainMode: 'NONE',
											longDistance: 'NOT_LONG_DISTANCE',
											preferentialService: false,
											iconType: 'EMPTY',
										},
										promoted: false,
										avgRating: '3.8',
										totalRatings: 100,
										new: false,
									},
									subtype: 'basic',
								},
							],
							totalRestaurants: 35,
						},
						subtype: 'personalized',
					},
					parentWidget: false,
				},
			],
			nextPageFetch: 0,
		},
		tid: 'b9e64854-34e9-49e2-840f-23117c9dbadf',
		sid: '5mk42586-bc41-4222-b36c-003011651792',
		deviceId: '81a5848c-a918-4774-361b-5b0678b6ebb7',
		csrfToken: '6gX9qScdt2y3-FD26XXDCZgOg0iVqX71DByCKqEM',
	};
export const IMG_CDN_URL = 'https://res.cloudinary.com/swiggy/image/upload/';

export const API_LINK =
	'https://www.swiggy.com/dapi/restaurants/list/v5?lat=26.4831584&lng=84.43655&page_type=DESKTOP_WEB_LISTING';
export const RESAURENT_ID_API_LINK =
	'https://www.swiggy.com/dapi/menu/v4/full?lat=26.4831584&lng=84.43655&menuId=';
