export const restaurantList = [
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '608033',
			name: "Domino's Pizza",
			uuid: '33638d50-b4a2-43a7-8dab-d77157988f2a',
			city: '10501',
			area: 'Gopalganj',
			totalRatingsString: '50+ ratings',
			cloudinaryImageId: 'xye5lg4snoojnwmjqamk',
			cuisines: ['Pizzas'],
			tags: [],
			costForTwo: 40000,
			costForTwoString: '₹400 FOR TWO',
			deliveryTime: 30,
			minDeliveryTime: 30,
			maxDeliveryTime: 30,
			slaString: '30 MINS',
			lastMileTravel: 0,
			slugs: {
				restaurant: 'dominos-pizza-gopalganj-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address:
				'Ground Floor, Janak Super Market,College Road, Goplaganj,Bihar:841427',
			locality: 'Gopalganj',
			parentId: 2456,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			hasSurge: false,
			sla: {
				restaurantId: '608033',
				deliveryTime: 30,
				minDeliveryTime: 30,
				maxDeliveryTime: 30,
				lastMileTravel: 0,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.3',
			totalRatings: 50,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '218749',
			name: 'Gaurishankar Sudh Misthan Bhandar',
			uuid: 'e5dac5bc-9772-4156-a419-0c017e002956',
			city: '10501',
			area: 'Haziapur',
			totalRatingsString: '100+ ratings',
			cloudinaryImageId: 'u0pdecwzqb36rdspanjg',
			cuisines: ['Sweets'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 43,
			minDeliveryTime: 43,
			maxDeliveryTime: 43,
			slaString: '43 MINS',
			lastMileTravel: 2.4000000953674316,
			slugs: {
				restaurant:
					'gaurishankar-sudh-misthan-bhandar-near-canara-bank-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'JADAVPUR ROAD NEAR CANARA BANK GOPALGANJ',
			locality: 'NEAR CANARA BANK',
			parentId: 86658,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.4 kms',
			hasSurge: false,
			sla: {
				restaurantId: '218749',
				deliveryTime: 43,
				minDeliveryTime: 43,
				maxDeliveryTime: 43,
				lastMileTravel: 2.4000000953674316,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '4.3',
			totalRatings: 100,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '487890',
			name: 'Roll Point',
			uuid: '3722212a-b2e7-47dd-955e-f1b1d737a947',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: 'Too Few Ratings',
			cloudinaryImageId: 'p0wwxlaaarh4kwxde5d0',
			cuisines: ['Snacks'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 46,
			minDeliveryTime: 46,
			maxDeliveryTime: 46,
			slaString: '46 MINS',
			lastMileTravel: 1.899999976158142,
			slugs: {
				restaurant:
					'food-palace-roll-point-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address:
				'YADOPUR ROAD W NO 12, NEAR AXICE BANK A, TM OPP SINGH MEDICAL, GOPALGANJ GOPALGAN, Gopalganj, Gopalganj, Gopalganj, Bihar - 841428',
			locality: 'Gopalganj Town',
			parentId: 3336,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.8 kms',
			hasSurge: false,
			sla: {
				restaurantId: '487890',
				deliveryTime: 46,
				minDeliveryTime: 46,
				maxDeliveryTime: 46,
				lastMileTravel: 1.899999976158142,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '--',
			totalRatings: 0,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '452131',
			name: 'Food Palace',
			uuid: 'a90f784e-ca60-46ba-966f-804efe488ef6',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: '50+ ratings',
			cloudinaryImageId: 's5vgple93gkqmwjx3cuk',
			cuisines: ['Indian', 'Fast Food', 'Chinese'],
			tags: [],
			costForTwo: 10000,
			costForTwoString: '₹100 FOR TWO',
			deliveryTime: 48,
			minDeliveryTime: 48,
			maxDeliveryTime: 48,
			slaString: '48 MINS',
			lastMileTravel: 1.899999976158142,
			slugs: {
				restaurant: 'food-palace-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'Near hotel kailash gopalganj, Bihar 841428, India',
			locality: 'Gopalganj Town',
			parentId: 81801,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '1.8 kms',
			hasSurge: false,
			sla: {
				restaurantId: '452131',
				deliveryTime: 48,
				minDeliveryTime: 48,
				maxDeliveryTime: 48,
				lastMileTravel: 1.899999976158142,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.6',
			totalRatings: 50,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '489796',
			name: 'The Ratna Cafe',
			uuid: 'c7c2acd9-8672-4a87-9def-4e47c968638d',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: '50+ ratings',
			cloudinaryImageId: 'o43gpbuw9pmnj5wyudgc',
			cuisines: ['South Indian'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 52,
			minDeliveryTime: 52,
			maxDeliveryTime: 52,
			slaString: '52 MINS',
			lastMileTravel: 2.0999999046325684,
			slugs: {
				restaurant:
					'pizza-express-king-plaza-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'SADHU MARKET, YADOPUR ROAD, GOPALGANJ',
			locality: 'Sadhu Market',
			parentId: 332876,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			sla: {
				restaurantId: '489796',
				deliveryTime: 52,
				minDeliveryTime: 52,
				maxDeliveryTime: 52,
				lastMileTravel: 2.0999999046325684,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.3',
			totalRatings: 50,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '220765',
			name: 'Hydrabadi Biryani House - 2',
			uuid: '8b91c464-dd40-4e47-b9bf-cebc2941bd48',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: 'Too Few Ratings',
			cloudinaryImageId: 'lef5gsjsobxgo9g1iele',
			cuisines: ['North Indian'],
			tags: [],
			costForTwo: 10000,
			costForTwoString: '₹100 FOR TWO',
			deliveryTime: 45,
			minDeliveryTime: 45,
			maxDeliveryTime: 45,
			slaString: '45 MINS',
			lastMileTravel: 2.799999952316284,
			slugs: {
				restaurant:
					'hydrabadi-biryani-house-2-near-ambedkar-chowk-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'AMBEDKAR CHOWK GOPALGANJ',
			locality: 'NEAR AMBEDKAR CHOWK',
			parentId: 105288,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '220765',
				deliveryTime: 45,
				minDeliveryTime: 45,
				maxDeliveryTime: 45,
				lastMileTravel: 2.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '--',
			totalRatings: 0,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '321002',
			name: 'PizzaExpress',
			uuid: '0efb2d9b-b63b-43c4-9a95-9a374452ddae',
			city: '10501',
			area: 'Police Line',
			totalRatingsString: '500+ ratings',
			cloudinaryImageId: 'gwnnl2ktfwxdezvcgdqy',
			cuisines: ['Indian', 'Chinese'],
			tags: [],
			costForTwo: 15000,
			costForTwoString: '₹150 FOR TWO',
			deliveryTime: 53,
			minDeliveryTime: 53,
			maxDeliveryTime: 53,
			slaString: '53 MINS',
			lastMileTravel: 2.0999999046325684,
			slugs: {
				restaurant: 'sudh-sakahari-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'Near Kailash Hotel Yadopur Road  Gopalganj',
			locality: 'Gopalganj Town',
			parentId: 3531,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			sla: {
				restaurantId: '321002',
				deliveryTime: 53,
				minDeliveryTime: 53,
				maxDeliveryTime: 53,
				lastMileTravel: 2.0999999046325684,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.3',
			totalRatings: 500,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '489777',
			name: 'The Biryani Mall',
			uuid: '4cdf95de-d228-452c-9df0-3362fb2d475d',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: '100+ ratings',
			cloudinaryImageId: 'azbvczriemzbbjkop39r',
			cuisines: ['Biryani', 'Chinese', 'North Indian', 'Mughlai'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 43,
			minDeliveryTime: 43,
			maxDeliveryTime: 43,
			slaString: '43 MINS',
			lastMileTravel: 2.0999999046325684,
			slugs: {
				restaurant:
					'pizza-express-the-biryani-mall-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'SADHU MARKET, YADOPUR ROAD, GOPALGANJ',
			locality: 'Sadhu Market',
			parentId: 205457,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '60% off',
				shortDescriptionList: [
					{
						meta: '60% off | Use TRYNEW',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '60% off up to ₹120 | Use code TRYNEW',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '60% OFF',
				shortDescriptionList: [
					{
						meta: 'Use TRYNEW',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '60% off up to ₹120 | Use code TRYNEW',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			sla: {
				restaurantId: '489777',
				deliveryTime: 43,
				minDeliveryTime: 43,
				maxDeliveryTime: 43,
				lastMileTravel: 2.0999999046325684,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.6',
			totalRatings: 100,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '425617',
			name: '7th Heaven',
			uuid: '9679f849-cb64-4474-aecf-3b85e5e04cc8',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: '20+ ratings',
			cloudinaryImageId: 'sshmgzi4ibm3myivvn36',
			cuisines: ['Bakery'],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 48,
			minDeliveryTime: 48,
			maxDeliveryTime: 48,
			slaString: '48 MINS',
			lastMileTravel: 2.5999999046325684,
			slugs: {
				restaurant:
					'7th-heaven-m/s-aarav-cake-&-cafe-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address:
				'Thana Road Ward No-12,Gopalganj.Prop-Sri  Prince Kumar,S/O-Sri Arun Kumar,At-Adarsh  Nagar,Siwan., Gopalganj, Gopalganj,  Bihar-841428',
			locality: 'Gopalganj Town',
			parentId: 19,
			unserviceable: true,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.5 kms',
			hasSurge: false,
			sla: {
				restaurantId: '425617',
				deliveryTime: 48,
				minDeliveryTime: 48,
				maxDeliveryTime: 48,
				lastMileTravel: 2.5999999046325684,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.6',
			totalRatings: 20,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '218763',
			name: 'K Chowdhary Sweet House',
			uuid: '638afce9-7ae6-45a0-a03c-2f782e7e8e9b',
			city: '10501',
			area: 'Banakata',
			totalRatingsString: '100+ ratings',
			cloudinaryImageId: 'lfvs1nsrqeppfskwwner',
			cuisines: ['Sweets'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 44,
			minDeliveryTime: 44,
			maxDeliveryTime: 44,
			slaString: '44 MINS',
			lastMileTravel: 2.5,
			slugs: {
				restaurant:
					'k-chowdhary-sweet-house-near-petrol-pump-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'K CHOWDHARY SWEET HOUSE, CINEMA ROAD GOPALGANJ',
			locality: 'NEAR PETROL PUMP',
			parentId: 112661,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.5 kms',
			hasSurge: false,
			sla: {
				restaurantId: '218763',
				deliveryTime: 44,
				minDeliveryTime: 44,
				maxDeliveryTime: 44,
				lastMileTravel: 2.5,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.9',
			totalRatings: 100,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '502941',
			name: 'Bihar Chatpata Biryani',
			uuid: 'da9b1456-f229-4eee-9b66-4fa03b5bb028',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: 'Too Few Ratings',
			cloudinaryImageId: 'iu2ijwgu2ha6tegx7oox',
			cuisines: ['Biryani', 'North Indian'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 47,
			minDeliveryTime: 47,
			maxDeliveryTime: 47,
			slaString: '47 MINS',
			lastMileTravel: 2.799999952316284,
			slugs: {
				restaurant:
					'bihar-chatpata-biryani-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'Ambedkar chowk,Near Hospital Gopalganj Bihar-841428',
			locality: 'Gopalganj Town',
			parentId: 301278,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '502941',
				deliveryTime: 47,
				minDeliveryTime: 47,
				maxDeliveryTime: 47,
				lastMileTravel: 2.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '--',
			totalRatings: 0,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '488436',
			name: 'Cheesy Chunks',
			uuid: '13620655-3813-4969-8268-368c625cf9e9',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: 'Too Few Ratings',
			cloudinaryImageId: 'a3trfcx5eegregzpijsn',
			cuisines: ['Ice Cream', 'Fast Food'],
			tags: [],
			costForTwo: 25000,
			costForTwoString: '₹250 FOR TWO',
			deliveryTime: 51,
			minDeliveryTime: 51,
			maxDeliveryTime: 51,
			slaString: '51 MINS',
			lastMileTravel: 2.200000047683716,
			slugs: {
				restaurant:
					'aarav-cake-&-cafe-cheesy-chunks-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address:
				'Thana Road Ward No-12,Gopalganj.Prop-Sri Prince Kumar,S/O-Sri Arun Kumar,At-Adarsh Nagar,Siwan., Gopalganj, Gopalganj, Bihar 841428',
			locality: 'Gopalganj Town',
			parentId: 293093,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.2 kms',
			hasSurge: false,
			sla: {
				restaurantId: '488436',
				deliveryTime: 51,
				minDeliveryTime: 51,
				maxDeliveryTime: 51,
				lastMileTravel: 2.200000047683716,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '--',
			totalRatings: 0,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '220762',
			name: 'Kumar Hotel',
			uuid: '84e8a91d-8965-4e30-8e94-b04465eae453',
			city: '10501',
			area: 'Thawe Road',
			totalRatingsString: '100+ ratings',
			cloudinaryImageId: 'j1dynsamgtndf5yfkkem',
			cuisines: ['Indian', 'Chinese'],
			tags: [],
			costForTwo: 25000,
			costForTwoString: '₹250 FOR TWO',
			deliveryTime: 55,
			minDeliveryTime: 55,
			maxDeliveryTime: 55,
			slaString: '55 MINS',
			lastMileTravel: 3.5999999046325684,
			slugs: {
				restaurant:
					'kumar-hotel-near-gopalganj-bus-stand-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address: 'THAWE ROAD , NEAR GOPALGANJ BUS STAND GOPALGANJ',
			locality: 'NEAR GOPALGANJ BUS STAND',
			parentId: 121763,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.5 kms',
			hasSurge: false,
			sla: {
				restaurantId: '220762',
				deliveryTime: 55,
				minDeliveryTime: 55,
				maxDeliveryTime: 55,
				lastMileTravel: 3.5999999046325684,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.6',
			totalRatings: 100,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '260443',
			name: 'Chaska Restaurant',
			uuid: 'd3a090eb-76f9-4de7-a362-8a1aa97d78f2',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'zn3zow3avdpqugav97qg',
			cuisines: ['North Indian', 'Italian', 'Chinese'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 49,
			minDeliveryTime: 49,
			maxDeliveryTime: 49,
			slaString: '49 MINS',
			lastMileTravel: 2.4000000953674316,
			slugs: {
				restaurant: 'chaska-restaurant-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address:
				'Lal Palace, Yadavpur Rd, below Canara Bank, Jalpurwan, Haziapur, Gopalganj, Bihar 841428',
			locality: 'Gopalganj Town',
			parentId: 3877,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2.4 kms',
			hasSurge: false,
			sla: {
				restaurantId: '260443',
				deliveryTime: 49,
				minDeliveryTime: 49,
				maxDeliveryTime: 49,
				lastMileTravel: 2.4000000953674316,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '3.6',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '433921',
			name: 'Tandoori House',
			uuid: 'd916c7cd-d82a-43b7-8cce-598f4e462f38',
			city: '10501',
			area: 'Gopalganj Town',
			totalRatingsString: 'Too Few Ratings',
			cloudinaryImageId: 'pe2epdgugt2y8pqfp99n',
			cuisines: ['North Indian'],
			tags: [],
			costForTwo: 20000,
			costForTwoString: '₹200 FOR TWO',
			deliveryTime: 51,
			minDeliveryTime: 51,
			maxDeliveryTime: 51,
			slaString: '51 MINS',
			lastMileTravel: 2.0999999046325684,
			slugs: {
				restaurant:
					'food-point-&-tandoori-house-gopalganj-town-gopalganj-town',
				city: 'gopalganj',
			},
			cityState: '10501',
			address:
				'Yadopur road near Cenra bank indian overseas bank compound Gopalaganj, Gopalganj, Gopalganj, Gopalganj, Bihar, 841428',
			locality: 'Gopalganj Town',
			parentId: 15087,
			unserviceable: true,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹80 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: '',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '2 kms',
			hasSurge: false,
			sla: {
				restaurantId: '433921',
				deliveryTime: 51,
				minDeliveryTime: 51,
				maxDeliveryTime: 51,
				lastMileTravel: 2.0999999046325684,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE_WITH_BANNER',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: false,
			avgRating: '--',
			totalRatings: 0,
			new: false,
		},
		subtype: 'basic',
	},
];
export const IMG_CDN_URL =
	'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

export const API_LINK =
	'https://www.swiggy.com/dapi/restaurants/list/v5?lat=26.4831584&lng=84.43655&page_type=DESKTOP_WEB_LISTING';
export const RESAURENT_ID_API_LINK =
	'https://www.swiggy.com/dapi/menu/v4/full?lat=26.4831584&lng=84.43655&menuId=';
